In [ ]:
import torch
from torch import nn
import torch.nn.functional as F

import numpy as np
import matplotlib.pyplot as plt

In [ ]:
with open('/content/drive/MyDrive/Deep_learning-datasets/shakespeare.txt','r',encoding='utf8') as f:
  text = f.read()

In [ ]:
type(text)

str

In [ ]:
print(text[:1000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [ ]:
len(text)

5445609

In [ ]:
all_characters = set(text)

In [ ]:
len(all_characters)

84

In [ ]:
decoder = dict(enumerate(all_characters))

In [ ]:
decoder

{0: 'n',
 1: 'f',
 2: 'J',
 3: 'g',
 4: '8',
 5: 'w',
 6: 'l',
 7: 'd',
 8: '|',
 9: 'y',
 10: 'c',
 11: 'a',
 12: 'R',
 13: 'O',
 14: '"',
 15: '4',
 16: 'F',
 17: '7',
 18: 'M',
 19: 'G',
 20: ']',
 21: '6',
 22: 'I',
 23: '1',
 24: '0',
 25: ':',
 26: 'Z',
 27: 'h',
 28: 't',
 29: 'o',
 30: '?',
 31: '`',
 32: 'B',
 33: '[',
 34: '\n',
 35: 'U',
 36: '9',
 37: ')',
 38: 'r',
 39: '_',
 40: 'P',
 41: 'N',
 42: 'k',
 43: '5',
 44: 'q',
 45: ',',
 46: 'i',
 47: 'L',
 48: 'S',
 49: 'm',
 50: 'H',
 51: 'Y',
 52: 'V',
 53: "'",
 54: '(',
 55: '2',
 56: 's',
 57: 'b',
 58: 'e',
 59: 'p',
 60: 'v',
 61: '&',
 62: 'E',
 63: 'A',
 64: 'Q',
 65: 'D',
 66: '.',
 67: 'K',
 68: '}',
 69: '-',
 70: ';',
 71: 'C',
 72: 'T',
 73: 'X',
 74: 'W',
 75: 'x',
 76: 'u',
 77: ' ',
 78: '<',
 79: '3',
 80: '>',
 81: 'z',
 82: 'j',
 83: '!'}

In [ ]:
encoder = {char:ind for ind,char in decoder.items()}

In [ ]:
encoder

{'n': 0,
 'f': 1,
 'J': 2,
 'g': 3,
 '8': 4,
 'w': 5,
 'l': 6,
 'd': 7,
 '|': 8,
 'y': 9,
 'c': 10,
 'a': 11,
 'R': 12,
 'O': 13,
 '"': 14,
 '4': 15,
 'F': 16,
 '7': 17,
 'M': 18,
 'G': 19,
 ']': 20,
 '6': 21,
 'I': 22,
 '1': 23,
 '0': 24,
 ':': 25,
 'Z': 26,
 'h': 27,
 't': 28,
 'o': 29,
 '?': 30,
 '`': 31,
 'B': 32,
 '[': 33,
 '\n': 34,
 'U': 35,
 '9': 36,
 ')': 37,
 'r': 38,
 '_': 39,
 'P': 40,
 'N': 41,
 'k': 42,
 '5': 43,
 'q': 44,
 ',': 45,
 'i': 46,
 'L': 47,
 'S': 48,
 'm': 49,
 'H': 50,
 'Y': 51,
 'V': 52,
 "'": 53,
 '(': 54,
 '2': 55,
 's': 56,
 'b': 57,
 'e': 58,
 'p': 59,
 'v': 60,
 '&': 61,
 'E': 62,
 'A': 63,
 'Q': 64,
 'D': 65,
 '.': 66,
 'K': 67,
 '}': 68,
 '-': 69,
 ';': 70,
 'C': 71,
 'T': 72,
 'X': 73,
 'W': 74,
 'x': 75,
 'u': 76,
 ' ': 77,
 '<': 78,
 '3': 79,
 '>': 80,
 'z': 81,
 'j': 82,
 '!': 83}

In [ ]:
encoded_text = np.array([encoder[char] for char in text])

In [ ]:
encoded_text[:500]

array([34, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77,
       77, 77, 77, 77, 77, 23, 34, 77, 77, 16, 38, 29, 49, 77,  1, 11, 46,
       38, 58, 56, 28, 77, 10, 38, 58, 11, 28, 76, 38, 58, 56, 77,  5, 58,
       77,  7, 58, 56, 46, 38, 58, 77, 46,  0, 10, 38, 58, 11, 56, 58, 45,
       34, 77, 77, 72, 27, 11, 28, 77, 28, 27, 58, 38, 58, 57,  9, 77, 57,
       58, 11, 76, 28,  9, 53, 56, 77, 38, 29, 56, 58, 77, 49, 46,  3, 27,
       28, 77,  0, 58, 60, 58, 38, 77,  7, 46, 58, 45, 34, 77, 77, 32, 76,
       28, 77, 11, 56, 77, 28, 27, 58, 77, 38, 46, 59, 58, 38, 77, 56, 27,
       29, 76,  6,  7, 77, 57,  9, 77, 28, 46, 49, 58, 77,  7, 58, 10, 58,
       11, 56, 58, 45, 34, 77, 77, 50, 46, 56, 77, 28, 58,  0,  7, 58, 38,
       77, 27, 58, 46, 38, 77, 49, 46,  3, 27, 28, 77, 57, 58, 11, 38, 77,
       27, 46, 56, 77, 49, 58, 49, 29, 38,  9, 25, 34, 77, 77, 32, 76, 28,
       77, 28, 27, 29, 76, 77, 10, 29,  0, 28, 38, 11, 10, 28, 58,  7, 77,
       28, 29, 77, 28, 27

In [ ]:
decoder[54]

'('

In [ ]:
def one_hot_encoder(encoded_text,num_uni_chars):
  one_hot = np.zeros((encoded_text.size,num_uni_chars))
  one_hot = one_hot.astype(np.float32)
  one_hot[np.arange(one_hot.shape[0]),encoded_text.flatten()] = 1.0
  one_hot = one_hot.reshape((*encoded_text.shape,num_uni_chars))
  return one_hot

In [ ]:
arr = np.array([1,2,0])

In [ ]:
one_hot_encoder(arr,3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
example_text = np.arange(10)

In [ ]:
example_text

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
example_text.reshape((5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
def generate_batches(encoded_text, samp_per_batch=10, seq_len=50):
    char_per_batch = samp_per_batch * seq_len
    num_batches_avail = int(len(encoded_text)/char_per_batch)
    encoded_text = encoded_text[:num_batches_avail * char_per_batch]
    encoded_text = encoded_text.reshape((samp_per_batch, -1))
    for n in range(0, encoded_text.shape[1], seq_len):
        x = encoded_text[:, n:n+seq_len]
        y = np.zeros_like(x)
        try:
            y[:, :-1] = x[:, 1:]
            y[:, -1]  = encoded_text[:, n+seq_len]
        except:
            y[:, :-1] = x[:, 1:]
            y[:, -1] = encoded_text[:, 0]
        yield x, y

In [ ]:
sample_text = np.arange(20)

In [ ]:
sample_text

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
batch_generator = generate_batches(sample_text,samp_per_batch=2,seq_len=5)

In [ ]:
x,y = next(batch_generator)

In [ ]:
x

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [ ]:
y

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [ ]:
class CharModel(nn.Module):
  def __init__(self,all_chars,num_hidden=256,num_layers=4,drop_prob=0.5,use_gpu=False):
    super().__init__()
    self.drop_prob = drop_prob
    self.num_layers = num_layers
    self.num_hidden = num_hidden
    self.use_gpu = use_gpu
    self.all_chars = all_chars
    self.decoder = dict(enumerate(all_chars))
    self.encoder = {char:ind for ind,char in decoder.items()}
    self.lstm = nn.LSTM(len(self.all_chars),num_hidden,num_layers,dropout=drop_prob,batch_first=True)
    self.dropout = nn.Dropout(drop_prob)
    self.fc_linear = nn.Linear(num_hidden,len(self.all_chars))
  def forward(self,x,hidden):
    lstm_output,hidden = self.lstm(x,hidden)
    drop_output = self.dropout(lstm_output)
    drop_output = drop_output.contiguous().view(-1,self.num_hidden)
    final_out = self.fc_linear(drop_output)
    return final_out,hidden
  def hidden_state(self,batch_size):
    if self.use_gpu:
      hidden = (torch.zeros(self.num_layers,batch_size,self.num_hidden).cuda(),
                torch.zeros(self.num_layers,batch_size,self.num_hidden).cuda())
    else:
      hidden = (torch.zeros(self.num_layers,batch_size,self.num_hidden),
                torch.zeros(self.num_layers,batch_size,self.num_hidden))
    return hidden

In [ ]:
model = CharModel(all_chars=all_characters,num_hidden=512,num_layers=3,drop_prob=0.5,use_gpu=True)

In [ ]:
total_param = []
for p in model.parameters():
  total_param.append(int(p.numel()))

In [ ]:
sum(total_param)

5470292

In [ ]:
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)
criterion = nn.CrossEntropyLoss()

In [ ]:
train_percent = 0.9

In [ ]:
train_ind = int(len(encoded_text) * (train_percent))

In [ ]:
train_data = encoded_text[:train_ind]
val_data = encoded_text[train_ind:]

In [ ]:
len(train_data)

4901048

In [ ]:
len(val_data)

544561

In [ ]:
epochs = 60
batch_size = 100
seq_len = 100
tracker = 0
num_char = max(encoded_text) + 1

In [ ]:
model.train()
if model.use_gpu:
  model.cuda()
for i in range(epochs):
  hidden = model.hidden_state(batch_size)
  for x,y in generate_batches(train_data,batch_size,seq_len):
    tracker += 1
    x = one_hot_encoder(x,num_char)
    inputs = torch.from_numpy(x)
    targets = torch.from_numpy(y)
    if model.use_gpu:
      inputs = inputs.cuda()
      targets = targets.cuda()
    hidden = tuple([state.data for state in hidden])
    model.zero_grad()
    lstm_output,hidden = model.forward(inputs,hidden)
    loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
    loss.backward()
    nn.utils.clip_grad_norm_(model.parameters(),max_norm=5)
    optimizer.step()
    if tracker % 25 == 0:
      val_hidden = model.hidden_state(batch_size)
      val_losses = []
      model.eval()
      for x,y in generate_batches(val_data,batch_size,seq_len):
        x = one_hot_encoder(x,num_char)
        inputs = torch.from_numpy(x)
        targets = torch.from_numpy(y)
        if model.use_gpu:
          inputs = inputs.cuda()
          targets = targets.cuda()
        val_hidden = tuple([state.data for state in val_hidden])
        lstm_output,val_hidden = model.forward(inputs,val_hidden)
        val_loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
        val_losses.append(val_loss.item())
      model.train()
      print(f"EPOCH: {i} STEP: {tracker} VAL_LOSS: {val_loss.item()}")

EPOCH: 0 STEP: 25 VAL_LOSS: 3.205142021179199
EPOCH: 0 STEP: 50 VAL_LOSS: 3.1936755180358887
EPOCH: 0 STEP: 75 VAL_LOSS: 3.1919937133789062
EPOCH: 0 STEP: 100 VAL_LOSS: 3.189558744430542
EPOCH: 0 STEP: 125 VAL_LOSS: 3.074559450149536
EPOCH: 0 STEP: 150 VAL_LOSS: 2.9705491065979004
EPOCH: 0 STEP: 175 VAL_LOSS: 2.8625385761260986
EPOCH: 0 STEP: 200 VAL_LOSS: 2.7379813194274902
EPOCH: 0 STEP: 225 VAL_LOSS: 2.6514999866485596
EPOCH: 0 STEP: 250 VAL_LOSS: 2.5337698459625244
EPOCH: 0 STEP: 275 VAL_LOSS: 2.4220330715179443
EPOCH: 0 STEP: 300 VAL_LOSS: 2.32315731048584
EPOCH: 0 STEP: 325 VAL_LOSS: 2.2567105293273926
EPOCH: 0 STEP: 350 VAL_LOSS: 2.194070816040039
EPOCH: 0 STEP: 375 VAL_LOSS: 2.145573139190674
EPOCH: 0 STEP: 400 VAL_LOSS: 2.1019225120544434
EPOCH: 0 STEP: 425 VAL_LOSS: 2.0594897270202637
EPOCH: 0 STEP: 450 VAL_LOSS: 2.044118881225586
EPOCH: 0 STEP: 475 VAL_LOSS: 1.9981765747070312
EPOCH: 1 STEP: 500 VAL_LOSS: 1.9742612838745117
EPOCH: 1 STEP: 525 VAL_LOSS: 1.9453418254852295
EPO

In [ ]:
model_name = 'hidden512_layers3_shakes.net'

In [ ]:
torch.save(model.state_dict(),model_name)

In [ ]:
def predict_next_char(model,char,hidden=None,k=1):
  encoded_text = model.encoder[char]
  encoded_text = np.array([[encoded_text]])
  encoded_text = one_hot_encoder(encoded_text,len(model.all_chars))
  inputs = torch.from_numpy(encoded_text)
  if model.use_gpu:
    inputs = inputs.cuda()
  hidden = tuple([state.data for state in hidden])
  lstm_out,hidden = model(inputs,hidden)
  probs = F.softmax(lstm_out,dim=1).data
  if model.use_gpu:
    probs = probs.cpu()
  probs,index_positions = probs.topk(k)
  index_positions = index_positions.numpy().squeeze()
  probs = probs.numpy().flatten()
  probs = probs/probs.sum()
  char = np.random.choice(index_positions,p=probs)
  return model.decoder[char],hidden

In [ ]:
def generate_text(model,size,seed='The',k=1):
  if model.use_gpu:
    model.cuda()
  else:
    model.cpu()
  model.eval()
  output_chars = [c for c in seed]
  hidden = model.hidden_state(1)
  for char in seed:
    char,hidden = predict_next_char(model,char,hidden,k=k)
  output_chars.append(char)
  for i in range(size):
    char,hidden = predict_next_char(model,output_chars[-1],hidden,k=k)
    output_chars.append(char)
  return ''.join(output_chars)

In [ ]:
print(generate_text(model,1000,seed='The ',k=3))

The contempts, the world, the door of the commonwealth, and the sense to the King's

    What is't?
  CASCA. Well, I'll not have my life as I have dead;
    And this was seen with me.
  COUNTESS. If you do, my lord,
    The watch, that have no passage on my heart,
    I would have struck the story to your sister.
    Then to the sense of many things are stood.
    Then that too much that she's a most affair,
    And therefore seek me there against the sense,
    And see the service of the state of honour,
    And sometime shall I think that the sun that shall have
    An exproved monster, and she shall set me with me.
    I am an angry, so much are they all.
    Thou shalt not, she is some thing to be so for thee,
    To be a state as to my soul to thine
    As we are as a man till she was thine.
    I will be too much seasons to thy son.
    I would not think of my design to th' mark,
    And will not be a soul to think of this.
  BASSANIO. Well, I'll see you to the way. If I should b